[package]
name = "bookstore"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
sqlx = { version = "0.8.2", features = ["postgres", "runtime-tokio-rustls"] }
tokio = { version = "1.40.0", features = ["full"] }
